services:
  hotel-api:
    build: .
    ports:
      - 3500:3500
    environment:
      - JWT_TOKEN_SECRET="e2bcbb591b0bd03ec1cae7ed467b1f509faf3057dd41662654964d1d1b22079f8442e4ed56be7a63bf528715a7797406c245bd38b463269d342e50cf6480d605"
    volumes:
      - ./src:/user/src/app/src
  booking-db:
    container_name: hotel-booking
    image: postgres:16
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "26042001"
      POSTGRES_DB: nestJS-booking
    ports:
      - 5432:5432
 